-- 코드를 입력하세요
SELECT A.CAR_ID
     , A.CAR_TYPE
     , A.DAILY_FEE*30*(1-DISCOUNT_RATE*0.01) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON A.CAR_TYPE = B.CAR_TYPE
   AND TO_NUMBER(RTRIM(B.DURATION_TYPE,'일 이상')) = 30
 WHERE A.CAR_TYPE IN ('SUV', '세단')
   AND A.CAR_ID NOT IN (
                        SELECT DISTINCT CAR_ID
                          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE TO_DATE('20221101', 'YYYY-MM-DD') BETWEEN START_DATE 
                           AND END_DATE
                            OR TO_DATE('20221130', 'YYYY-MM-DD') BETWEEN START_DATE 
                           AND END_DATE
                        )
   AND A.DAILY_FEE*30*(1-DISCOUNT_RATE*0.01) BETWEEN 500000 AND 2000000-0.00001
 ORDER BY FEE DESC, A.CAR_TYPE, CAR_ID DESC;