-- 자동차 종류가 '세단' 또는 'SUV'인 자동차 중 2022년 11월 1일 ~ 2022년 11월 30일 까지 대여가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서
-- 자동차 ID, 자동차 종류, 대여 금액(컬럼명은 FEE로)을 출력하라! * 1.대여 금액으로 내림차순, 2.자동차 종류 기준 오름차순, 3. 자동차 ID기준 내림차순
SELECT  A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30*(1-(DISCOUNT_RATE/100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
AND B.DURATION_TYPE = '30일 이상'
WHERE A.CAR_TYPE IN ('SUV', '세단')
AND A.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE
    OR '2022-11-30' BETWEEN START_DATE AND END_DATE
)
AND A.DAILY_FEE*30*(1-DISCOUNT_RATE*0.01) BETWEEN 500000 AND 2000000-0.00001
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC