     SELECT C.ID AS ID
       FROM ECOLI_DATA A
 INNER JOIN ECOLI_DATA B
         ON B.PARENT_ID = A.ID
 INNER JOIN ECOLI_DATA C
         ON C.PARENT_ID = B.ID         
      WHERE A.PARENT_ID IS NULL
   ORDER BY ID