-- 0시부터 23시까지, 각 시간대별로 입양이 몇건이 발생헀는지 조회하라!
-- 단, 결과는 시간대 순으로 정렬하라!
WITH RECURSIVE HOUR_RECURSIVE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOUR_RECURSIVE
    WHERE HOUR < 23
)

SELECT A.HOUR, IFNULL(B.COUNT, 0) AS COUNT
FROM HOUR_RECURSIVE A 
     LEFT JOIN (SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(DATE_FORMAT(DATETIME, '%H')) AS COUNT
                FROM ANIMAL_OUTS
                GROUP BY DATE_FORMAT(DATETIME, '%H')
                ORDER BY DATE_FORMAT(DATETIME, '%H')) B
            ON A.HOUR = B.HOUR;