WITH RECURSIVE GEN_TABLE AS (
    SELECT ID
         , 1 AS GENERATION
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
     UNION ALL 
    SELECT A.ID
         , B.GENERATION + 1 AS GENERATION
      FROM ECOLI_DATA A
INNER JOIN GEN_TABLE  B
        ON B.ID = A.PARENT_ID
)
SELECT COUNT(*) AS COUNT
     , A.GENERATION
  FROM GEN_TABLE A
 WHERE NOT EXISTS (
                   SELECT 1
                     FROM ECOLI_DATA AA
                    WHERE AA.PARENT_ID = A.ID
                  )
 GROUP BY A.GENERATION
 ORDER BY A.GENERATION