SELECT C.ITEM_ID
         , C.ITEM_NAME
         , C.RARITY
      FROM ITEM_INFO A
INNER JOIN ITEM_TREE B
        ON A.ITEM_ID = B.PARENT_ITEM_ID
       AND A.RARITY  = 'RARE'
INNER JOIN ITEM_INFO C
        ON B.ITEM_ID = C.ITEM_ID
  ORDER BY C.ITEM_ID DESC;