-- 서울에 위치한 식당들의 식당 ID, 식당 이름, 음식 종류, 즐겨찾기 수, 주소, 리뷰 평균 점수를 조회하는 SQL문을 작성해라!
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I LEFT OUTER JOIN 
     REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE (I.ADDRESS LIKE '%서울특별시%' OR I.ADDRESS LIKE '%서울시%')  AND R.REVIEW_ID IS NOT NULL
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;